# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Mon, 27 Feb 2017 11:46:14 +0000
*               @ALL          0
*               @user         8
