<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: tadone
 * Date: Tue, 28 Feb 2017 15:38:16 +0000
 */

$conf['title'] = 'Tadone\'s Wiki';
$conf['template'] = 'bootstrap3';
$conf['license'] = 'gnufdl';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
$conf['userewrite'] = '1';
$conf['plugin']['syntaxhighlighter4']['theme'] = 'theme-midnight.css';
$conf['tpl']['bootstrap3']['tableStyle'] = 'striped,bordered,condensed,responsive';
$conf['tpl']['bootstrap3']['tocPosition'] = 'left';

// end auto-generated content
