<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: tadone
 * Date: Mon, 27 Feb 2017 12:33:44 +0000
 */

$conf['title'] = 'Tadone\'s Wiki';
$conf['template'] = 'bootstrap3';
$conf['license'] = 'gnufdl';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
$conf['userewrite'] = '2';

// end auto-generated content
